# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER witos

# 挂载目录
VOLUME /home/witos
# 创建目录
RUN mkdir -p /home/witos
# 指定路径
WORKDIR /home/witos
# 复制jar文件到路径
COPY ./jar/ems-file.jar /home/witos/ems-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","ems-file.jar"]
