package com.witos.ems.server.service.impl;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.witos.common.core.exception.ServiceException;
import com.witos.common.core.utils.StringUtils;
import com.witos.ems.server.auth.EmsAuthScopeService;
import com.witos.ems.server.domain.entity.EmsCompany;
import com.witos.ems.server.domain.entity.EmsDevice;
import com.witos.ems.server.domain.entity.EmsStation;
import com.witos.ems.server.mapper.EmsCompanyMapper;
import com.witos.ems.server.mapper.EmsDeviceMapper;
import com.witos.ems.server.mapper.EmsStationMapper;
import com.witos.ems.server.service.EmsDeviceService;
import com.witos.ems.server.support.EmsPageSupport;
import com.witos.ems.server.support.EmsRequestSupport;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Open-source device CRUD; telemetry is generated by the PC frontend. */
@Service
public class EmsDeviceServiceImpl implements EmsDeviceService
{
    @Resource private EmsDeviceMapper deviceMapper;
    @Resource private EmsCompanyMapper companyMapper;
    @Resource private EmsStationMapper stationMapper;
    @Resource private EmsAuthScopeService authScopeService;

    @Override
    public IPage<Map<String, Object>> list(Map<String, String> query, String fixedDeviceType)
    {
        Map<String, Object> params = queryMap(query);
        if (StringUtils.isNotEmpty(fixedDeviceType)) params.put("deviceType", fixedDeviceType);
        return deviceMapper.selectDevicePage(EmsPageSupport.page(), params, authScopeService.currentScope());
    }

    @Override
    public List<Map<String, Object>> listAll(Map<String, String> query, String fixedDeviceType)
    {
        Map<String, Object> params = queryMap(query);
        if (StringUtils.isNotEmpty(fixedDeviceType)) params.put("deviceType", fixedDeviceType);
        return deviceMapper.selectDeviceList(params, authScopeService.currentScope());
    }

    @Override
    public Map<String, Object> get(Long id)
    {
        return deviceMapper.selectDeviceDetail(id, authScopeService.currentScope());
    }

    @Override
    public List<Map<String, Object>> bindCandidates(Map<String, String> query)
    {
        // Component/SN discovery is not part of the open-source build.
        return new ArrayList<Map<String, Object>>();
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public Map<String, Object> save(Map<String, Object> body, String fixedDeviceType)
    {
        Long deviceId = EmsRequestSupport.coalesceId(body, "deviceId", "id");
        Long companyId = EmsRequestSupport.requiredLong(body, "companyId", "公司不能为空");
        Long stationId = EmsRequestSupport.requiredLong(body, "stationId", "电站不能为空");
        String deviceName = EmsRequestSupport.stringValue(body.get("deviceName"));
        if (StringUtils.isEmpty(deviceName)) throw new ServiceException("设备名称不能为空");

        EmsCompany company = validateCompany(companyId);
        EmsStation station = validateStation(companyId, stationId);
        if (!Objects.equals(company.getTenantId(), station.getTenantId()))
            throw new ServiceException("设备所属公司与电站不属于同一租户");
        EmsDevice current = deviceId == null ? null : requireDevice(deviceId);
        Long tenantId = current == null ? station.getTenantId() : current.getTenantId();
        if (!Objects.equals(tenantId, station.getTenantId())) throw new ServiceException("不能将设备迁移到其他租户");
        validateController(deviceId, tenantId, companyId, stationId, EmsRequestSupport.asLong(body.get("controllerId")));

        EmsDevice device = new EmsDevice();
        device.setId(deviceId);
        device.setTenantId(tenantId);
        device.setCompanyId(companyId);
        device.setStationId(stationId);
        device.setControllerId(EmsRequestSupport.asLong(body.get("controllerId")));
        device.setDeviceCode(EmsRequestSupport.stringValue(body.get("deviceCode")));
        device.setDeviceName(deviceName);
        device.setDeviceType(StringUtils.isNotEmpty(fixedDeviceType) ? fixedDeviceType
                : EmsRequestSupport.defaultString(body.get("deviceType"), "OTHER"));
        device.setRatedCapacity(EmsRequestSupport.asBigDecimal(body.get("ratedCapacity")));
        device.setModel(EmsRequestSupport.stringValue(body.get("model")));
        device.setSerialNo(EmsRequestSupport.stringValue(body.get("serialNo")));
        device.setManufacturer(EmsRequestSupport.stringValue(body.get("manufacturer")));
        device.setFirmwareVersion(EmsRequestSupport.stringValue(body.get("firmwareVersion")));
        if (body.containsKey("lastHeartbeatTime")) device.setLastHeartbeatTime(EmsRequestSupport.nullableTimestamp(body.get("lastHeartbeatTime")));
        device.setControllerVersion(EmsRequestSupport.stringValue(body.get("controllerVersion")));
        if (body.containsKey("installDate")) device.setInstallDate(EmsRequestSupport.nullableTimestamp(body.get("installDate")));
        device.setCommStatus(EmsRequestSupport.defaultString(body.get("commStatus"), "UNKNOWN"));
        device.setStatus(EmsRequestSupport.defaultString(body.get("status"), "NORMAL"));
        device.setRemark(EmsRequestSupport.stringValue(body.get("remark")));
        if (deviceId == null)
        {
            deviceMapper.insert(device);
            deviceId = device.getId();
        }
        else deviceMapper.updateById(device);
        return get(deviceId);
    }

    @Override public Map<String, Object> unbind(Long id) { return get(id); }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public boolean remove(Long id)
    {
        requireDevice(id);
        return deviceMapper.deleteById(id) > 0;
    }

    private Map<String, Object> queryMap(Map<String, String> query)
    {
        return query == null ? new LinkedHashMap<String, Object>() : new LinkedHashMap<String, Object>(query);
    }

    private EmsCompany validateCompany(Long companyId)
    {
        Map<String, Object> detail = companyMapper.selectCompanyDetail(companyId, authScopeService.currentScope());
        if (detail == null || detail.isEmpty()) throw new ServiceException("公司超出当前授权范围");
        EmsCompany company = companyMapper.selectById(companyId);
        if (company == null) throw new ServiceException("公司不存在");
        return company;
    }

    private EmsStation validateStation(Long companyId, Long stationId)
    {
        Map<String, Object> detail = stationMapper.selectStationDetail(stationId, authScopeService.currentScope());
        if (detail == null || detail.isEmpty()) throw new ServiceException("电站超出当前授权范围");
        Long stationCompanyId = EmsRequestSupport.asLong(detail.get("companyId"));
        if (stationCompanyId != null && !stationCompanyId.equals(companyId)) throw new ServiceException("设备所属电站与公司不匹配");
        EmsStation station = stationMapper.selectById(stationId);
        if (station == null) throw new ServiceException("电站不存在");
        return station;
    }

    private void validateController(Long deviceId, Long tenantId, Long companyId, Long stationId, Long controllerId)
    {
        if (controllerId == null) return;
        if (deviceId != null && deviceId.equals(controllerId)) throw new ServiceException("所属控制器不能选择当前设备");
        EmsDevice controller = deviceMapper.selectById(controllerId);
        if (controller == null || !"0".equals(controller.getDelFlag())) throw new ServiceException("所属控制器不存在");
        if (!"CONTROLLER".equalsIgnoreCase(controller.getDeviceType())) throw new ServiceException("所属控制器类型不正确");
        if (!Objects.equals(tenantId, controller.getTenantId())) throw new ServiceException("所属控制器与设备不属于同一租户");
        if (controller.getCompanyId() != null && !controller.getCompanyId().equals(companyId)) throw new ServiceException("所属控制器与公司不匹配");
        if (controller.getStationId() != null && !controller.getStationId().equals(stationId)) throw new ServiceException("所属控制器与电站不匹配");
    }

    private EmsDevice requireDevice(Long deviceId)
    {
        Map<String, Object> detail = deviceMapper.selectDeviceDetail(deviceId, authScopeService.currentScope());
        if (detail == null || detail.isEmpty()) throw new ServiceException("设备不存在或超出当前授权范围");
        EmsDevice device = deviceMapper.selectById(deviceId);
        if (device == null || !"0".equals(device.getDelFlag())) throw new ServiceException("设备不存在");
        return device;
    }
}
